/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ImgWithMetadata {
  id: number
  name: string
  x: number
  y: number
  w: number
  h: number
  data: Uint8Array
}
export function numScreens(): number
export function captureScreen(n: number): ImgWithMetadata | null
export function focusedWindowId(): number | null
export function captureWindow(id: number): ImgWithMetadata | null
